apiVersion: v1
kind: Pod
metadata:
  name: builder
  labels:
    app: easy-gate
spec:
  containers:
    - name: builder
      image: quay.io/podman/stable
      command:
        - cat
      tty: true
      securityContext:
        privileged: true
      requests:
        memory: "256Mi"
        cpu: "500m"
      limits:
        memory: "1024Mi"
        cpu: "1000m"
