apiVersion: v1
kind: Pod
metadata:
  name: builder
  labels:
    app: easy-gate
spec:
  containers:
    - name: builder
      image: tomkukral/buildah:latest
      command:
        - sleep
        - "1000000"
      tty: true
      securityContext:
        privileged: true
