pipeline {
    agent {
        kubernetes {
            defaultContainer 'podman'
            yamlFile 'jenkins/PodmanPod.yaml'
        }
    }

    environment {
        IMAGE = "kubemaster/easy-gate"
        TAG = ${GIT_COMMIT,length=6}
    }

    stages {
        stage('Build easy-gate image') {
            steps {
                sh "echo ${TAG}"
                // sh "podman build -t ${IMAGE}:${TAG} . && \
                // podman login -u kubemaster -p T!gris.1 && \
                // podman push ${IMAGE}:${TAG}"
            }
        }
    }
}