pipeline {
    agent {
        kubernetes {
            defaultContainer 'podman'
            yamlFile 'jenkins/PodmanPod.yaml'
        }
    }

    environment {
        REGISTRY = "docker.io"
        IMAGE = "kubemaster/easy-gate"
        TAG = GIT_COMMIT.take(7)
    }

    stages {
        stage('Build easy-gate image') {
            steps {
                sh "podman build -t ${REGISTRY}/${IMAGE}:${TAG} ."
                sh "podman login -u kubemaster -p T!gris.1"
                sh "podman push ${REGISTRY}/${IMAGE}:${TAG}"
            }
        }
    }
}
