pipeline {
    agent any

    environment {
        IMAGE = "kubemaster/easy-gate"
        TAG = "jenkins"
        // TAG = $GIT_COMMIT
    }

    stages {
        stage('Build easy-gate image') {
            agent {
                kubernetes {
                    yamlFile 'jenkins/BuilderPod.yaml'
                }
            }
            stages {
                stage('Build and push image') {
                    steps {
                        sh "podman build -t ${IMAGE}:${TAG} . && \
                        podman login -u kubemaster -p T!gris.1 && \
                        podman push ${IMAGE}:${TAG}"
                    }
                }
            }
        }
    }
}